name: Release Charts and Images

on:
  push:
    branches:
    - master
    paths:
    - 'charts/**'
    - 'src/**'
    - 'Dockerfile*'
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io

jobs:
  release-chart:
    name: Release Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Chart Info
      id: chart_info
      run: |
        VERSION=$(grep '^version:' charts/cluster-secret/Chart.yaml | awk '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
        config: cr.yaml
        charts_dir: charts
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    outputs:
      version: ${{ steps.chart_info.outputs.version }}

  build-image:
    name: Build Image (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    needs: release-chart
    permissions:
      packages: write
    strategy:
      matrix:
        include:
        - arch: amd64
          runner: ubuntu-latest
          platform: linux/amd64
        - arch: arm64
          runner: ubuntu-24.04-arm
          platform: linux/arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set image name lowercase
      id: image_name
      run: echo "name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ steps.image_name.outputs.name }}
        tags: ${{ needs.release-chart.outputs.version }}-${{ matrix.arch }} latest-${{ matrix.arch }}
        platforms: ${{ matrix.platform }}
        containerfiles: |
          ./Dockerfile.gh

    - name: Push to GHCR
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

  create-manifest:
    name: Create Multi-arch Manifest
    runs-on: ubuntu-latest
    needs: [release-chart, build-image]
    permissions:
      packages: write
    steps:
    - name: Set image name lowercase
      id: image_name
      run: echo "name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create and push manifest
      env:
        VERSION: ${{ needs.release-chart.outputs.version }}
        IMAGE_NAME: ${{ steps.image_name.outputs.name }}
      run: |
        docker manifest create \
          ${{ env.IMAGE_REGISTRY }}/${IMAGE_NAME}:${VERSION} \
          --amend ${{ env.IMAGE_REGISTRY }}/${IMAGE_NAME}:${VERSION}-amd64 \
          --amend ${{ env.IMAGE_REGISTRY }}/${IMAGE_NAME}:${VERSION}-arm64
        docker manifest push ${{ env.IMAGE_REGISTRY }}/${IMAGE_NAME}:${VERSION}

        docker manifest create \
          ${{ env.IMAGE_REGISTRY }}/${IMAGE_NAME}:latest \
          --amend ${{ env.IMAGE_REGISTRY }}/${IMAGE_NAME}:latest-amd64 \
          --amend ${{ env.IMAGE_REGISTRY }}/${IMAGE_NAME}:latest-arm64
        docker manifest push ${{ env.IMAGE_REGISTRY }}/${IMAGE_NAME}:latest
